version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    depends_on:
      - backend
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=${db_host}
      - DB_PORT=${db_port}
      - DB_USER=${db_user}
      - DB_PASSWORD=${db_password}
      - DB_NAME=${db_name}
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    ports:
      - 5432:${db_port}
    environment:
      - POSTGRES_PASSWORD=${db_password}
      - POSTGRES_USER=${db_user}
      - POSTGRES_DB=${db_name}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data:
  node_modules: